# Generated by Django 4.2.3 on 2023-07-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('date_added', models.TimeField(auto_now_add=True)),
                ('posts', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['date_added', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('address_line1', models.CharField(max_length=120)),
                ('address_city', models.CharField(max_length=30)),
                ('address_state', models.CharField(max_length=3)),
                ('address_zip', models.PositiveIntegerField()),
                ('birthdate', models.DateField(max_length=11)),
                ('info', models.TextField(max_length=500)),
                ('parents', models.CharField(max_length=200)),
                ('teachers', models.CharField(max_length=200)),
                ('students', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=50)),
                ('classes', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
