# Generated by Django 4.2.3 on 2023-07-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('phone', models.CharField(max_length=15)),
                ('address_line1', models.CharField(max_length=120)),
                ('address_city', models.CharField(max_length=30)),
                ('address_state', models.CharField(max_length=3)),
                ('address_zip', models.PositiveIntegerField()),
                ('birthdate', models.DateField(max_length=11)),
                ('info', models.TextField(max_length=500)),
                ('parents', models.CharField(max_length=200)),
                ('teachers', models.CharField(max_length=200)),
                ('students', models.CharField(max_length=200)),
                ('classes', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
