# Generated by Django 4.2.3 on 2023-07-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_appuser_address_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='birthdate',
            field=models.DateField(blank=True, max_length=11, null=True),
        ),
    ]
