# Generated by Django 4.2.3 on 2023-07-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_user_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='First Name', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=120),
        ),
    ]
