# Generated by Django 4.2.3 on 2023-07-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_appuser_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='address_line1',
            field=models.CharField(max_length=120, verbose_name='address lin 1'),
        ),
    ]
