# Generated by Django 4.2.3 on 2023-07-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_appuser_date_joined_alter_appuser_address_line1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='date_joined',
        ),
    ]
