# Generated by Django 4.2.3 on 2023-07-13 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_messageboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('address_line1', models.CharField(max_length=120)),
                ('address_city', models.CharField(max_length=30)),
                ('address_state', models.CharField(max_length=3)),
                ('address_zip', models.PositiveIntegerField()),
                ('birthdate', models.DateField(max_length=11)),
                ('info', models.TextField(max_length=500)),
                ('parents', models.CharField(max_length=200)),
                ('teachers', models.CharField(max_length=200)),
                ('students', models.CharField(max_length=200)),
                ('classes', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='messageboard',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
