# Generated by Django 4.2.3 on 2023-07-13 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_profile_delete_user_messageboard_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageboard',
            name='user',
        ),
    ]
